server:
  port: 8081
  error:
    include-message: always
spring:
  datasource:
    url: postgres://fsstysxhtvsebp:ed852796c00f650bf533d2b3aad378408ba525c7a35eab51b91047600aa5e3cd@ec2-54-75-26-218.eu-west-1.compute.amazonaws.com:5432/da5v6ra9jhk40g
    username: fsstysxhtvsebp
    password: ed852796c00f650bf533d2b3aad378408ba525c7a35eab51b91047600aa5e3cd
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
  servlet:
    multipart:
      max-request-size: 20MB
      max-file-size: 20MB
springdoc:
  swagger-ui:
    path: /docs

telegram_bot_username: open_budget_ovoz_ber_bot
telegram_bot_botToken: 5531876841:AAFuW0OeJ17cMrJq5GxQ0yZbLEsr004-Is8

#special_code: '+998909741228 +998332002022'



#https://matn.uz/


#https://matn.uz/
